#
# Test file to illustrate how parameters can be transferred
#

Mz : 91.1876
Mw : 80.385
sin2thW : 
  value : 0.23127
  step  : 0.02  

Order : NLO
NFlavour : 5

hf_scheme : ZMVFNS

# We want to fit alphaS, making this explicitly:
AalphaS: 
  value: 20.0
  step:  0.0
  prior: 20.0  
  priorUnc: 0.1
  min: 19.0
  max: 21.0


Order: NNLO
muF: 1.0
muR: 1.0

