#
# Test file to illustrate how parameters can be transferred
#

Mz : 91.1876
Mw : 80.385
sin2thW : 
  value : 0.23127
  step  : 0.02

Order : NLO
NFlavour : 5

mch : 1.43 
mbt : 4.5

# speficify HF scheme:
hf_scheme_DISNC : 
  value : 'RT_DISNC'
  'HERA1+2 NCep 920' : 'BaseDISNC'
#  1 : BaseDISNC  

# We want to fit alphaS, making this explicitly:
AalphaS: 
  value: 20.0
  step:  0.0
  prior: 20.0  
  priorUnc: 0.1
  min: 19.0
  max: 21.0


muF: 1.0
muR: 1.0

# Example of vectors

testVec :  [1., 2., 3., 4.]
